# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/developers/enterpriseapi/api/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class PreviewDocument(BaseModel):
    """
    PreviewDocument
    """ # noqa: E501
    object: Optional[Annotated[str, Field(min_length=15, strict=True, max_length=15)]] = Field(default='PreviewDocument', description="Name of the object")
    in_library: Optional[StrictBool] = Field(default=None, description="Determines if the preview document is present in the UniCourt Library or not.", alias="inLibrary")
    added_to_library_date: Optional[Annotated[str, Field(min_length=25, strict=True, max_length=25)]] = Field(default=None, description="Date and time when the preview document was downloaded and added to the UniCourt CrowdSourced Library.", alias="addedToLibraryDate")
    download_api: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Link to get the file url for the preview document which is already present in the UniCourt CrowdSourced Library.", alias="downloadAPI")
    __properties: ClassVar[List[str]] = ["object", "inLibrary", "addedToLibraryDate", "downloadAPI"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PreviewDocument from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if added_to_library_date (nullable) is None
        # and model_fields_set contains the field
        if self.added_to_library_date is None and "added_to_library_date" in self.model_fields_set:
            _dict['addedToLibraryDate'] = None

        # set to None if download_api (nullable) is None
        # and model_fields_set contains the field
        if self.download_api is None and "download_api" in self.model_fields_set:
            _dict['downloadAPI'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PreviewDocument from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object": obj.get("object") if obj.get("object") is not None else 'PreviewDocument',
            "inLibrary": obj.get("inLibrary"),
            "addedToLibraryDate": obj.get("addedToLibraryDate"),
            "downloadAPI": obj.get("downloadAPI")
        })
        return _obj


