"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.court_availability_api import CourtAvailabilityApi  # noqa: E501


class TestCourtAvailabilityApi(unittest.TestCase):
    """CourtAvailabilityApi unit test stubs"""

    def setUp(self):
        self.api = CourtAvailabilityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_court_coverage(self):
        """Test case for get_court_coverage

        Gets Court Coverage of all courts of specific type.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
