"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.case_document import CaseDocument
from openapi_client.model.exception import Exception
from openapi_client.model.export_file import ExportFile
globals()['CaseDocument'] = CaseDocument
globals()['Exception'] = Exception
globals()['ExportFile'] = ExportFile
from openapi_client.model.case_document_order_callback import CaseDocumentOrderCallback


class TestCaseDocumentOrderCallback(unittest.TestCase):
    """CaseDocumentOrderCallback unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCaseDocumentOrderCallback(self):
        """Test CaseDocumentOrderCallback"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CaseDocumentOrderCallback()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
