"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.contact import Contact
from openapi_client.model.norm_judge_public_data_aba_ratings import NormJudgePublicDataAbaRatings
from openapi_client.model.norm_judge_public_data_bio import NormJudgePublicDataBio
from openapi_client.model.norm_judge_public_data_education_array_inner import NormJudgePublicDataEducationArrayInner
from openapi_client.model.norm_judge_public_data_judicial_source import NormJudgePublicDataJudicialSource
from openapi_client.model.norm_judge_public_data_name_history_array_inner import NormJudgePublicDataNameHistoryArrayInner
from openapi_client.model.service_history import ServiceHistory
globals()['Contact'] = Contact
globals()['NormJudgePublicDataAbaRatings'] = NormJudgePublicDataAbaRatings
globals()['NormJudgePublicDataBio'] = NormJudgePublicDataBio
globals()['NormJudgePublicDataEducationArrayInner'] = NormJudgePublicDataEducationArrayInner
globals()['NormJudgePublicDataJudicialSource'] = NormJudgePublicDataJudicialSource
globals()['NormJudgePublicDataNameHistoryArrayInner'] = NormJudgePublicDataNameHistoryArrayInner
globals()['ServiceHistory'] = ServiceHistory
from openapi_client.model.norm_judge_public_data import NormJudgePublicData


class TestNormJudgePublicData(unittest.TestCase):
    """NormJudgePublicData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNormJudgePublicData(self):
        """Test NormJudgePublicData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NormJudgePublicData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
