"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.associated_norm_attorney import AssociatedNormAttorney
globals()['AssociatedNormAttorney'] = AssociatedNormAttorney
from openapi_client.model.associated_norm_attorney_response import AssociatedNormAttorneyResponse


class TestAssociatedNormAttorneyResponse(unittest.TestCase):
    """AssociatedNormAttorneyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssociatedNormAttorneyResponse(self):
        """Test AssociatedNormAttorneyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AssociatedNormAttorneyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
