"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.docket_entry_primary_documents import DocketEntryPrimaryDocuments
from openapi_client.model.docket_entry_secondary_documents import DocketEntrySecondaryDocuments
from openapi_client.model.referenced_docket_number import ReferencedDocketNumber
from openapi_client.model.source_structured_data import SourceStructuredData
globals()['DocketEntryPrimaryDocuments'] = DocketEntryPrimaryDocuments
globals()['DocketEntrySecondaryDocuments'] = DocketEntrySecondaryDocuments
globals()['ReferencedDocketNumber'] = ReferencedDocketNumber
globals()['SourceStructuredData'] = SourceStructuredData
from openapi_client.model.docket_entry import DocketEntry


class TestDocketEntry(unittest.TestCase):
    """DocketEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocketEntry(self):
        """Test DocketEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DocketEntry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
