"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.jurisdiction_geo import JurisdictionGeo
globals()['JurisdictionGeo'] = JurisdictionGeo
from openapi_client.model.jurisdiction_geo_response import JurisdictionGeoResponse


class TestJurisdictionGeoResponse(unittest.TestCase):
    """JurisdictionGeoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJurisdictionGeoResponse(self):
        """Test JurisdictionGeoResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JurisdictionGeoResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
