"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.case_count_analytics_by_court import CaseCountAnalyticsByCourt
globals()['CaseCountAnalyticsByCourt'] = CaseCountAnalyticsByCourt
from openapi_client.model.case_count_analytics_by_court_response import CaseCountAnalyticsByCourtResponse


class TestCaseCountAnalyticsByCourtResponse(unittest.TestCase):
    """CaseCountAnalyticsByCourtResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCaseCountAnalyticsByCourtResponse(self):
        """Test CaseCountAnalyticsByCourtResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CaseCountAnalyticsByCourtResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
