"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.bar_source_data_board_certifications_array_inner import BarSourceDataBoardCertificationsArrayInner


class TestBarSourceDataBoardCertificationsArrayInner(unittest.TestCase):
    """BarSourceDataBoardCertificationsArrayInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBarSourceDataBoardCertificationsArrayInner(self):
        """Test BarSourceDataBoardCertificationsArrayInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BarSourceDataBoardCertificationsArrayInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
