"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.case_count_analytics_by_case_type import CaseCountAnalyticsByCaseType
globals()['CaseCountAnalyticsByCaseType'] = CaseCountAnalyticsByCaseType
from openapi_client.model.case_count_analytics_by_case_type_response import CaseCountAnalyticsByCaseTypeResponse


class TestCaseCountAnalyticsByCaseTypeResponse(unittest.TestCase):
    """CaseCountAnalyticsByCaseTypeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCaseCountAnalyticsByCaseTypeResponse(self):
        """Test CaseCountAnalyticsByCaseTypeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CaseCountAnalyticsByCaseTypeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
