"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.norm_judge_public_data_education_array_inner import NormJudgePublicDataEducationArrayInner


class TestNormJudgePublicDataEducationArrayInner(unittest.TestCase):
    """NormJudgePublicDataEducationArrayInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNormJudgePublicDataEducationArrayInner(self):
        """Test NormJudgePublicDataEducationArrayInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NormJudgePublicDataEducationArrayInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
