"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.attorney_law_firm import AttorneyLawFirm
from openapi_client.model.attorney_type import AttorneyType
from openapi_client.model.contact import Contact
from openapi_client.model.party_attorney_associations import PartyAttorneyAssociations
from openapi_client.model.possible_norm_attorney import PossibleNormAttorney
from openapi_client.model.possible_norm_law_firm import PossibleNormLawFirm
globals()['AttorneyLawFirm'] = AttorneyLawFirm
globals()['AttorneyType'] = AttorneyType
globals()['Contact'] = Contact
globals()['PartyAttorneyAssociations'] = PartyAttorneyAssociations
globals()['PossibleNormAttorney'] = PossibleNormAttorney
globals()['PossibleNormLawFirm'] = PossibleNormLawFirm
from openapi_client.model.attorney import Attorney


class TestAttorney(unittest.TestCase):
    """Attorney unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttorney(self):
        """Test Attorney"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Attorney()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
