"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.authentication_api import AuthenticationApi  # noqa: E501


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self):
        self.api = AuthenticationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_generate_new_token(self):
        """Test case for generate_new_token

        Generate new token to access API.  # noqa: E501
        """
        pass

    def test_invalidate_all_tokens(self):
        """Test case for invalidate_all_tokens

        API to invalidate all access tokens.  # noqa: E501
        """
        pass

    def test_invalidate_token(self):
        """Test case for invalidate_token

        API to invalidate the access token.  # noqa: E501
        """
        pass

    def test_list_all_token_ids(self):
        """Test case for list_all_token_ids

        API to list all the access tokens Id.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
