"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.billing_cycle_usage_response_api_calls_billable import BillingCycleUsageResponseApiCallsBillable
from openapi_client.model.billing_cycle_usage_response_api_calls_credited import BillingCycleUsageResponseApiCallsCredited
from openapi_client.model.billing_cycle_usage_response_api_calls_made import BillingCycleUsageResponseApiCallsMade
globals()['BillingCycleUsageResponseApiCallsBillable'] = BillingCycleUsageResponseApiCallsBillable
globals()['BillingCycleUsageResponseApiCallsCredited'] = BillingCycleUsageResponseApiCallsCredited
globals()['BillingCycleUsageResponseApiCallsMade'] = BillingCycleUsageResponseApiCallsMade
from openapi_client.model.daily_usage_response import DailyUsageResponse


class TestDailyUsageResponse(unittest.TestCase):
    """DailyUsageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDailyUsageResponse(self):
        """Test DailyUsageResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DailyUsageResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
