"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.case_count_analytics_by_court_location import CaseCountAnalyticsByCourtLocation
globals()['CaseCountAnalyticsByCourtLocation'] = CaseCountAnalyticsByCourtLocation
from openapi_client.model.case_count_analytics_by_court_location_response import CaseCountAnalyticsByCourtLocationResponse


class TestCaseCountAnalyticsByCourtLocationResponse(unittest.TestCase):
    """CaseCountAnalyticsByCourtLocationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCaseCountAnalyticsByCourtLocationResponse(self):
        """Test CaseCountAnalyticsByCourtLocationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CaseCountAnalyticsByCourtLocationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
