"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.case_type_group import CaseTypeGroup


class TestCaseTypeGroup(unittest.TestCase):
    """CaseTypeGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCaseTypeGroup(self):
        """Test CaseTypeGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CaseTypeGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
