"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.case_analytics_api import CaseAnalyticsAPI
from openapi_client.model.judge_analytics_api import JudgeAnalyticsAPI
from openapi_client.model.norm_judge_public_data import NormJudgePublicData
globals()['CaseAnalyticsAPI'] = CaseAnalyticsAPI
globals()['JudgeAnalyticsAPI'] = JudgeAnalyticsAPI
globals()['NormJudgePublicData'] = NormJudgePublicData
from openapi_client.model.norm_judge import NormJudge


class TestNormJudge(unittest.TestCase):
    """NormJudge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNormJudge(self):
        """Test NormJudge"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NormJudge()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
