"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.associated_norm_law_firm import AssociatedNormLawFirm
globals()['AssociatedNormLawFirm'] = AssociatedNormLawFirm
from openapi_client.model.associated_norm_law_firm_response import AssociatedNormLawFirmResponse


class TestAssociatedNormLawFirmResponse(unittest.TestCase):
    """AssociatedNormLawFirmResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssociatedNormLawFirmResponse(self):
        """Test AssociatedNormLawFirmResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AssociatedNormLawFirmResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
