"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.case_count_analytics_by_jurisdiction_geo import CaseCountAnalyticsByJurisdictionGeo
globals()['CaseCountAnalyticsByJurisdictionGeo'] = CaseCountAnalyticsByJurisdictionGeo
from openapi_client.model.case_count_analytics_by_jurisdiction_geo_response import CaseCountAnalyticsByJurisdictionGeoResponse


class TestCaseCountAnalyticsByJurisdictionGeoResponse(unittest.TestCase):
    """CaseCountAnalyticsByJurisdictionGeoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCaseCountAnalyticsByJurisdictionGeoResponse(self):
        """Test CaseCountAnalyticsByJurisdictionGeoResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CaseCountAnalyticsByJurisdictionGeoResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
