"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.case_timeline import CaseTimeline
from openapi_client.model.sos_data_preview import SOSDataPreview
globals()['CaseTimeline'] = CaseTimeline
globals()['SOSDataPreview'] = SOSDataPreview
from openapi_client.model.associated_norm_party import AssociatedNormParty


class TestAssociatedNormParty(unittest.TestCase):
    """AssociatedNormParty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssociatedNormParty(self):
        """Test AssociatedNormParty"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AssociatedNormParty()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
