"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cause_of_action_additional_data import CauseOfActionAdditionalData


class TestCauseOfActionAdditionalData(unittest.TestCase):
    """CauseOfActionAdditionalData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCauseOfActionAdditionalData(self):
        """Test CauseOfActionAdditionalData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CauseOfActionAdditionalData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
