"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.possible_norm_party_score_constituents import PossibleNormPartyScoreConstituents
globals()['PossibleNormPartyScoreConstituents'] = PossibleNormPartyScoreConstituents
from openapi_client.model.possible_norm_party import PossibleNormParty


class TestPossibleNormParty(unittest.TestCase):
    """PossibleNormParty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPossibleNormParty(self):
        """Test PossibleNormParty"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PossibleNormParty()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
