"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.case_track_schedule import CaseTrackSchedule
from openapi_client.model.case_update_request import CaseUpdateRequest
globals()['CaseTrackSchedule'] = CaseTrackSchedule
globals()['CaseUpdateRequest'] = CaseUpdateRequest
from openapi_client.model.case_track_request import CaseTrackRequest


class TestCaseTrackRequest(unittest.TestCase):
    """CaseTrackRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCaseTrackRequest(self):
        """Test CaseTrackRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CaseTrackRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
