"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.attorney_analytics_api import AttorneyAnalyticsAPI
from openapi_client.model.bar_record import BarRecord
from openapi_client.model.case_analytics_api import CaseAnalyticsAPI
from openapi_client.model.similar_norm_attorney import SimilarNormAttorney
globals()['AttorneyAnalyticsAPI'] = AttorneyAnalyticsAPI
globals()['BarRecord'] = BarRecord
globals()['CaseAnalyticsAPI'] = CaseAnalyticsAPI
globals()['SimilarNormAttorney'] = SimilarNormAttorney
from openapi_client.model.norm_attorney import NormAttorney


class TestNormAttorney(unittest.TestCase):
    """NormAttorney unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNormAttorney(self):
        """Test NormAttorney"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NormAttorney()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
