"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.extracted_fields import ExtractedFields
from openapi_client.model.raw_ordered_data import RawOrderedData
globals()['ExtractedFields'] = ExtractedFields
globals()['RawOrderedData'] = RawOrderedData
from openapi_client.model.source_structured_data import SourceStructuredData


class TestSourceStructuredData(unittest.TestCase):
    """SourceStructuredData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSourceStructuredData(self):
        """Test SourceStructuredData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SourceStructuredData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
