"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.pacer_search_receipt import PACERSearchReceipt


class TestPACERSearchReceipt(unittest.TestCase):
    """PACERSearchReceipt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPACERSearchReceipt(self):
        """Test PACERSearchReceipt"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PACERSearchReceipt()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
