name: SDK test with Python Script on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install UniCourt Python SDK       
        run: python setup.py install
      - name: Checking secrets exist
        run: echo "CLIENT_ID is ${{secrets.CLIENT_ID}} and CLIENT_SECRET is ${{secrets.CLIENT_SECRET}}"
      - name: Checking env's exist
        run: echo "CLIENT_ID is $CLIENT_ID and CLIENT_SECRET is $CLIENT_SECRET"
      - name: Run SDK test
        run: cd test && python base.py --exclude TestPacer